from collections.abc import Iterable, Iterator, Mapping
from typing import Any, Callable, Generic, Optional, TypeVar, overload

K = TypeVar("K")
V = TypeVar("V")
T = TypeVar("T")

class IndexedOrderedDict(Generic[K, V]):
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: K) -> V: ...
    def __setitem__(self, key: K, value: V) -> None: ...
    def __delitem__(self, key: K) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[K]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    @overload
    def __or__(self, other: "IndexedOrderedDict[K, V]") -> "IndexedOrderedDict[K, V]": ...
    @overload
    def __or__(self, other: Mapping[K, V]) -> "IndexedOrderedDict[K, V]": ...
    def __ior__(self, other: Mapping[K, V]) -> "IndexedOrderedDict[K, V]": ...
    def __reversed__(self) -> Iterator[K]: ...
    def keys(self) -> list[K]: ...
    def values(self) -> list[V]: ...
    def items(self) -> list[tuple[K, V]]: ...
    def clear(self) -> None: ...
    def copy(self) -> "IndexedOrderedDict[K, V]": ...
    @overload
    def get(self, key: K) -> Optional[V]: ...
    @overload
    def get(self, key: K, default: T) -> V | T: ...
    @overload
    def pop(self, key: K) -> V: ...
    @overload
    def pop(self, key: K, default: T) -> V | T: ...
    def popitem(self, last: bool = True) -> tuple[K, V]: ...
    @overload
    def setdefault(self, key: K) -> Optional[V]: ...
    @overload
    def setdefault(self, key: K, default: V) -> V: ...
    def move_to_end(self, key: K, last: bool = True) -> None: ...
    def sort(
        self,
        *,
        key: Optional[Callable[[K], Any]] = None,
        reverse: bool = False,
    ) -> None: ...
    @overload
    def update(self, other: "IndexedOrderedDict[K, V]") -> None: ...
    @overload
    def update(self, other: Mapping[K, V]) -> None: ...
    def index_of(self, key: K) -> int: ...
    @classmethod
    def fromkeys(
        cls,
        iterable: Iterable[K],
        value: T = None,
    ) -> "IndexedOrderedDict[K, T]": ...
    def __getstate__(self) -> tuple[tuple[K, V], ...]: ...
    def __setstate__(self, state: tuple[tuple[K, V], ...]) -> None: ...
    def __repr__(self) -> str: ...
