from typing import Any, Dict, Iterator

class IndexedOrderedDict(Dict[Any, Any]):
    def __init__(*args: Any, **kwargs: Any) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __delitem__(self, key: Any) -> None: ...
    def __contains__(self, key: Any) -> bool: ...
    def __iter__(self) -> Any: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __or__(self, other: Any) -> 'IndexedOrderedDict': ...
    def __ior__(self, other: Any) -> 'IndexedOrderedDict': ...
    def __reversed__(self) -> Iterator[Any]: ...
    def keys(self) -> Any: ...
    def values(self) -> Any: ...
    def items(self) -> Any: ...
    def clear(self) -> None: ...
    def copy(self) -> 'IndexedOrderedDict': ...
    def get(self, key: Any, default: Any = None) -> Any: ...
    def pop(self, key: Any, default: Any = None) -> Any: ...
    def popitem(self, last: bool = True) -> Any: ...
    def setdefault(self, key: Any, default: Any = None) -> Any: ...
    def sort(self, key: Any = None, reverse: bool = False) -> None: ...
    def update(self, other: Any) -> None: ...
    def __repr__(self) -> str: ...
dict.fromkeys